@startuml

start

:Open repository page;
:Click "New Issue";
:Display issue creation form;
:User fills in title, description, labels, and assignee;
:Click "Create Issue";

if (Are inputs valid?) then (Yes)
    :System saves the issue to the database;
    :Sets status to "Open";
    :Displays page with the new issue;
else (No)
    :Show error message;
    :User can correct inputs;
endif

stop

@enduml

