@startuml

title Use Case Diagram - MiniGitHub

left to right direction
/'top to bottom direction'/

actor "Visitor" as Visitor
actor "User" as User

package "Visitor System" {
    usecase "Browsing public repositories" as UC1
    usecase "Viewing user profiles" as UC2
    usecase "Registration" as UC3
    usecase "Login" as UC4
    
    (View Repoisotory) as UC13
    (View Profile) as UC14
    
}

package "User System" {
    usecase "Logout" as UC5
    (Profile management) as UC6
    (Creating a repository) as UC7
    (Committing changes) as UC8
    (Creating an issue) as UC10
    (Commenting on issue) as UC11
    (Deleting a repository) as UC12
    
    (Preview Selected Files) as UC15
    (Close an Issue) as UC16
    
    (Change Username) as UC17
    (Change Email) as UC18
}


Visitor <|-- User

' Relationships
Visitor --> UC1
Visitor --> UC2
Visitor --> UC3
/'Visitor --> UC13'/
/'Visitor --> UC14'/

User --> UC4
User --> UC5
User --> UC6
User --> UC7
User --> UC8
User --> UC10
User --> UC11
User --> UC12


' Extend relationships
' After registration, can log in
UC3 ..> UC4 : <<extend>>   
' Login allows profile management
UC4 ..> UC6 : <<extend>>   

UC1 <-- UC13 : <<extend>>
UC2 <-- UC14 : <<extend>>

UC8 <-- UC15 : <<extend>>
UC11 <-- UC16 : <<extend>>

UC6 <-- UC17 : <<extend>>
UC6 <-- UC18 : <<extend>>


@enduml

